name: 'ev_infrastructure_pipeline'
version: '1.0.0'
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  ev_infrastructure_pipeline:
    +materialized: table 


    